[CmdletBinding()]
param([Parameter(Position=0)][string]$InputPath,[switch]$Recursive,[int]$ExpectedRate=0,[int]$ExpectedChannels=0,[switch]$Loudness,[double]$LoudnessToleranceDb=3,[switch]$Json,[string]$Output,[switch]$Help)
. "$PSScriptRoot/lib/Common.ps1";. "$PSScriptRoot/lib/FFmpeg.ps1"
if($Help){'albumcontract BETA - find technical outliers in an audio delivery folder';'Usage: .\albumcontract.ps1 DIR [-Recursive] [-ExpectedRate HZ] [-ExpectedChannels N] [-Loudness] [-Json]';exit 0};if(-not $InputPath){[Console]::Error.WriteLine('directory required');exit 2};Assert-CDLDependencies
try{$files=@(Get-CDLAudioFiles $InputPath -Recursive:$Recursive)}catch{[Console]::Error.WriteLine($_.Exception.Message);exit 2};if(-not $files.Count){[Console]::Error.WriteLine('no supported audio files');exit 2}
$rows=@();foreach($f in $files){$rate=Get-CDLProbeValue $f sample_rate;$ch=Get-CDLProbeValue $f channels;$sf=Get-CDLProbeValue $f sample_fmt;$codec=Get-CDLProbeValue $f codec_name;$fmt=Get-CDLProbeValue $f format_name format;$l=$null;if($Loudness){$l=Get-CDLIntegratedLufs $f};$rows+=[pscustomobject][ordered]@{path=$f;sample_rate=if($rate){[int]$rate}else{$null};channels=if($ch){[int]$ch}else{$null};sample_format=$sf;codec=$codec;container=$fmt;integrated_lufs=$l}}
function Mode($vals){($vals|Group-Object|Sort-Object -Property @{Expression='Count';Descending=$true},@{Expression='Name';Descending=$false}|Select-Object -First 1).Name}
$dr=if($ExpectedRate){$ExpectedRate}else{[int](Mode @($rows.sample_rate))};$dc=if($ExpectedChannels){$ExpectedChannels}else{[int](Mode @($rows.channels))};$df=Mode @($rows.sample_format);$find=@();foreach($r in $rows){if($r.sample_rate -ne $dr){$find+=New-CDLFinding 'sample_rate_outlier' "sample rate $($r.sample_rate) differs from contract $dr" $r.path};if($r.channels -ne $dc){$find+=New-CDLFinding 'channel_count_outlier' "channel count $($r.channels) differs from contract $dc" $r.path};if($r.sample_format -ne $df){$find+=New-CDLFinding 'sample_format_outlier' "sample format $($r.sample_format) differs from dominant $df" $r.path}}
$status=if($find.Count){'review'}else{'ok'};$report=[ordered]@{tool='albumcontract';version=$script:CDLVersion;generated_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ');inputs=@($InputPath);dependencies=Get-CDLVersions;options=[ordered]@{recursive=[bool]$Recursive;loudness=[bool]$Loudness};measurements=[ordered]@{dominant_sample_rate=$dr;dominant_channels=$dc;dominant_sample_format=$df;files=$rows};findings=$find;status=$status};Write-CDLReport $report -Json:$Json -Output $Output -Text "albumcontract BETA: $($rows.Count) files, contract=${dr}Hz/${dc}ch/$df status=$status";if($find.Count){exit 1};exit 0
