[CmdletBinding()]
param([Parameter(Position=0)][string]$InputPath,[switch]$Recursive,[double]$ThresholdDb=-60,[ValidateRange(0.000001,[double]::MaxValue)][double]$MinSilence=0.10,[ValidateRange(0.0,[double]::MaxValue)][Nullable[double]]$MaxLeading,[ValidateRange(0.0,[double]::MaxValue)][Nullable[double]]$MaxTrailing,[switch]$Json,[string]$Output,[switch]$Help)
. "$PSScriptRoot/lib/Common.ps1"
if($Help){'batchsilence BETA - compare leading/trailing silence across a batch';'Usage: .\batchsilence.ps1 DIR [-ThresholdDb DB] [-MinSilence SEC] [-MaxLeading SEC] [-MaxTrailing SEC] [-Recursive] [-Json] [-Output path]';exit 0};if(-not $InputPath){[Console]::Error.WriteLine('directory required');exit 2};Assert-CDLDependencies
try{$files=@(Get-CDLAudioFiles $InputPath -Recursive:$Recursive)}catch{[Console]::Error.WriteLine($_.Exception.Message);exit 2};if(-not $files.Count){[Console]::Error.WriteLine('no supported audio files');exit 2}
$rows=@();$find=@();$inv=[Globalization.CultureInfo]::InvariantCulture
function Get-EdgeSilenceSeconds {param([string]$Path,[switch]$Reverse);$detect="silencedetect=noise=$($ThresholdDb.ToString($inv))dB:d=$($MinSilence.ToString($inv))";$filter=if($Reverse){"areverse,$detect"}else{$detect};$lines=& ffmpeg -hide_banner -nostats -i $Path -af $filter -f null - 2>&1;$started=$false;foreach($line in $lines){$s="$line";if(-not $started -and $s -match 'silence_start:\s*([-0-9.]+)'){$start=[double]::Parse($Matches[1],$inv);if($start -le 0.0001){$started=$true}else{return 0.0}}elseif($started -and $s -match 'silence_end:\s*([-0-9.]+)'){return [double]::Parse($Matches[1],$inv)}};return 0.0}
foreach($f in $files){$durText=Get-CDLProbeValue $f duration format;$dur=if($durText){[double]::Parse($durText,$inv)}else{0};$lead=Get-EdgeSilenceSeconds -Path $f;$trail=Get-EdgeSilenceSeconds -Path $f -Reverse;$rows+=[pscustomobject][ordered]@{path=$f;duration_seconds=$dur;leading_silence_seconds=$lead;trailing_silence_seconds=$trail;leading_ratio=if($dur){$lead/$dur}else{0};trailing_ratio=if($dur){$trail/$dur}else{0}};if($null -ne $MaxLeading -and $lead -gt $MaxLeading){$find+=New-CDLFinding 'excessive_leading_silence' "leading silence $lead exceeds $MaxLeading" $f};if($null -ne $MaxTrailing -and $trail -gt $MaxTrailing){$find+=New-CDLFinding 'excessive_trailing_silence' "trailing silence $trail exceeds $MaxTrailing" $f}}
$status=if($find.Count){'review'}else{'ok'};$report=[ordered]@{tool='batchsilence';version=$script:CDLVersion;generated_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ');inputs=@($InputPath);dependencies=Get-CDLVersions;options=[ordered]@{threshold_db=$ThresholdDb;min_silence=$MinSilence;max_leading=$MaxLeading;max_trailing=$MaxTrailing;recursive=[bool]$Recursive};measurements=[ordered]@{files=$rows};findings=$find;status=$status};Write-CDLReport $report -Json:$Json -Output $Output -Text "batchsilence BETA: $($rows.Count) files status=$status";if($find.Count){exit 1};exit 0
